# Generated by Django 3.1.7 on 2021-04-10 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_info', '0001_initial'),
        ('award_info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='项目名称')),
                ('projectType', models.CharField(choices=[('ns', '国家自然科学基金面上项目'), ('no', '国家自然科学基金其他项目'), ('nm', '国家自然科学基金重要项目'), ('ng', '国家自然科学基金重大项目'), ('dm', '国防科技重点实验基金项目'), ('p9', '973项目'), ('p8', '863项目'), ('ot', '其他')], default='ot', max_length=2, verbose_name='项目类型')),
                ('projectWork', models.CharField(max_length=256, verbose_name='工作任务')),
                ('SchoolYearInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='著作名称')),
                ('publishing_house', models.CharField(max_length=256, verbose_name='出版社')),
                ('contribution', models.CharField(max_length=256, verbose_name='工作量')),
                ('bookKey', models.CharField(max_length=256, verbose_name='书号')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
                ('publishType', models.CharField(max_length=256, verbose_name='编著类型')),
                ('authorAmount', models.IntegerField(default=1, verbose_name='作者人数')),
                ('authorNum', models.IntegerField(default=1, verbose_name='第几作者')),
                ('SchoolYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='专利名称')),
                ('classify', models.CharField(choices=[('ip', '发明专利'), ('ot', '其它')], default='ip', max_length=2, verbose_name='专利类别')),
                ('applyNumber', models.CharField(max_length=25, verbose_name='专利申请号')),
                ('applyTime', models.DateField(verbose_name='专利申请日期')),
                ('certificateNumber', models.CharField(blank=True, max_length=25, null=True, verbose_name='专利证书编号')),
                ('approveDate', models.DateField(blank=True, null=True, verbose_name='专利批准日期')),
                ('holdUnit', models.CharField(max_length=25, verbose_name='专利持有单位')),
                ('SchoolYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaperRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('publishDate', models.DateField(verbose_name='发表日期')),
                ('name', models.CharField(max_length=256, verbose_name='论文名称')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('magzineName', models.CharField(blank=True, max_length=256, null=True, verbose_name='期刊名称')),
                ('authOrder', models.CharField(choices=[('f', '第一作者'), ('s', '第二作者'), ('t', '第三作者'), ('r', '共同第一作者'), ('o', '其它')], default='f', max_length=1, verbose_name='作者顺序')),
                ('totalAuthor', models.IntegerField(default=2, verbose_name='作者人数')),
                ('postStatus', models.CharField(choices=[('po', '在线发表'), ('pa', '正式发表'), ('ot', '其它')], default='pa', max_length=2, verbose_name='发表状态')),
                ('totalReference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='他引状况')),
                ('conferenceChoice', models.CharField(choices=[('ic', '国际会议'), ('im', '重要期刊'), ('tm', '顶级期刊'), ('os', '其它SCI期刊'), ('om', '国际期刊'), ('nm', '国内期刊'), ('nc', '国内会议'), ('ot', '其它')], default='ot', max_length=2, verbose_name='期刊等级')),
                ('SchoolYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HonorTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('honorName', models.CharField(max_length=25, verbose_name='荣誉名称')),
                ('proclaimOrganization', models.CharField(max_length=25, verbose_name='颁发单位')),
                ('honorRank', models.CharField(choices=[('in', '国际级'), ('ac', '学院级'), ('ds', '省部级'), ('co', '学校级'), ('na', '国家级'), ('ot', '其他')], default='ac', max_length=2, verbose_name='荣誉级别')),
                ('issueDate', models.DateField(verbose_name='获得日期')),
                ('type', models.CharField(choices=[('ho', '荣誉称号'), ('ot', '其他成果')], default='ho', max_length=2, verbose_name='荣誉称号/其他成果')),
                ('SchoolYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=256, verbose_name='竞赛名称')),
                ('holder', models.CharField(max_length=256, verbose_name='主办单位')),
                ('awardName', models.CharField(max_length=25, verbose_name='奖项名称')),
                ('competeRange', models.CharField(choices=[('na', '全国'), ('in', '国际'), ('ds', '省市/区域'), ('lr', '校级'), ('cl', '学院'), ('ot', '其它')], default='na', max_length=2, verbose_name='获奖级别')),
                ('awardLevel', models.CharField(choices=[('u', '特等奖'), ('f', '一等奖'), ('s', '二等奖'), ('t', '三等奖'), ('r', '四等奖'), ('o', '其他')], default='f', max_length=1, verbose_name='本人获奖等级')),
                ('otherAward', models.CharField(blank=True, max_length=256, null=True, verbose_name='其他获奖等级')),
                ('teammateAmount', models.IntegerField(default=1, verbose_name='团队人数')),
                ('selfOrder', models.IntegerField(default=1, verbose_name='本人第几')),
                ('certificateID', models.CharField(blank=True, max_length=256, null=True, verbose_name='获奖证书编号')),
                ('certificateDistributeOrganizationName', models.CharField(blank=True, max_length=256, null=True, verbose_name='获奖证书颁发单位')),
                ('type', models.CharField(choices=[('ra', '科技获奖'), ('ia', '创新竞赛')], default='ia', max_length=2, verbose_name='(科技创新/竞赛)')),
                ('SchoolYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('awardName', models.CharField(max_length=25, verbose_name='奖学金名称')),
                ('AwardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award_info.awardinfo')),
                ('AwardYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grade_info.schoolyearinfo', verbose_name='获奖学年')),
                ('User', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
