# Generated by Django 3.1.7 on 2021-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardhistory',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='awardhistory',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='awardhistory',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='competitionrecord',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='competitionrecord',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='competitionrecord',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='honortitle',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='honortitle',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='honortitle',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='paperrecord',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='paperrecord',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='paperrecord',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='patentrecord',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='patentrecord',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='patentrecord',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='publishrecord',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='publishrecord',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='publishrecord',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='update_time',
        ),
    ]
