# Generated by Django 3.1.7 on 2021-04-10 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeinfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='gradeinfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='gradeinfo',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='update_time',
        ),
    ]
