# Generated by Django 3.1.7 on 2021-04-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_info', '0003_auto_20210410_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='ExtendMajor',
        ),
        migrations.DeleteModel(
            name='ExtendMajorInfo',
        ),
    ]
