# Generated by Django 3.1.7 on 2021-04-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_info', '0004_auto_20210410_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='update_time',
        ),
    ]
