# Generated by Django 3.1.7 on 2021-04-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade_info', '0006_auto_20210410_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorinfo',
            name='isPostgraduate',
        ),
    ]
