# Generated by Django 3.1.7 on 2021-04-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_info', '0007_remove_majorinfo_ispostgraduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorinfo',
            name='isPostgraduate',
            field=models.BooleanField(default=False, verbose_name='本科生/研究生'),
        ),
    ]
